### ISSUE TITLE
phpunit 10 support?

### ISSUE THREAD

**Issue by michondr** [webmozarts/strict-phpunit#1]
Hi, are you planing to update this library to support new phpunit?

**Comment by theofidry** [comment]
Sorry for the late reply; this will be added very soon.

**Comment by theofidry** [comment]
Note that internally we are still waiting on Prophecy support for PHPUnit 10 :/

**Comment by theofidry** [comment]
This has been added as of [7.10.0](https://github.com/webmozarts/strict-phpunit/releases/tag/7.10.0).
